import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { AdminStore } from './admin-store.mjs';
import { createApplication } from './app-server.mjs';
const root = fileURLToPath(new URL('.', import.meta.url));
const origin = new URL(process.env.APP_ORIGIN || 'http://localhost:3000');
const local = ['localhost','127.0.0.1','[::1]'].includes(origin.hostname);
if (origin.pathname !== '/' || origin.search || origin.hash || origin.username || origin.password) throw new Error('APP_ORIGIN deve conter somente protocolo, host e porta.');
if ((process.env.NODE_ENV === 'production' || !local) && origin.protocol !== 'https:') throw new Error('Use APP_ORIGIN com HTTPS em produção.');
const store = new AdminStore({ filename: process.env.ADMIN_DB_PATH || path.join(root, 'data/legado.sqlite') });
const server = http.createServer(createApplication({ store, origin: origin.origin, secureCookies: origin.protocol === 'https:' }));
server.requestTimeout = 15000;
server.headersTimeout = 15000;
server.listen(Number(process.env.PORT || 3000), process.env.HOST || '127.0.0.1', () => console.log(`Catálogo Legado: ${origin.origin}\nAdministração: ${origin.origin}/admin`));
for (const signal of ['SIGINT','SIGTERM']) process.on(signal, () => server.close(() => { store.close(); process.exit(0); }));